// _universal.ts — the UNIVERSAL prop every json-ui component accepts.
//
// Each component declares its OWN props with `z.object({ ... })` and then folds
// this universal prop in via `.extend(UNIVERSAL_PROPS.shape)`. The shape here
// mirrors the EXACT per-component JSON Schema the Python planner emits (see
// /src/fused/agent_core/widgets/schema/*.json), so the TS-side zod schemas and the
// server-side JSON Schemas stay in lockstep:
//
//   "style":   { "type": "string", optional, ... }      inline CSS declarations
//
// NOTE: there is intentionally NO universal `visible` prop — the Fused
// application has no node-level `visible` and lints component props with
// `.strict()`, so a `visible` key would break paste-compatibility. openfused's
// component set is a strict SUBSET of the application's (see spec/ui/json-ui.md).
//
// IMPORTANT: at render time `zod` is aliased to ../zod-stub (build.mjs), so the
// `.shape`/`.extend`/`.describe`/`.optional` calls below are NO-OPS that survive
// module load but produce nothing. The real schema only matters to the
// agent-facing catalog generated by generate.ts, which imports the REAL zod.
import { z } from "zod";

/**
 * The universal prop shared by every component.
 *
 * `style` — an OPTIONAL inline CSS declaration string merged OVER the
 *           component's built-in default styles (parsed with `parseStyle`).
 *
 * STYLING RULE (every JSON-UI author — agents and humans): components ship
 * sensible default styling (padding, spacing, layout, colors). PREFER THE
 * DEFAULTS — omit `style` in the common case and set it ONLY for a deliberate
 * override. Leaning on the defaults gives a consistent look across every JSON-UI
 * surface; ad-hoc `style` overrides drift from it. The string is merged over (it
 * overrides individual properties, never replaces) the defaults. See
 * packages/widgets/specs/authoring.md § The universal `style` prop.
 *
 * Optional: a node may omit it. Components fold `UNIVERSAL_PROPS.shape` into
 * their own `z.object({...})` via `.extend(UNIVERSAL_PROPS.shape)`.
 */
export const UNIVERSAL_PROPS = z.object({
  style: z
    .string()
    .optional()
    .describe(
      "Optional inline CSS, merged OVER the component's built-in defaults. PREFER THE DEFAULTS — omit this in the common case and set it ONLY for a deliberate override (it overrides individual properties, never replaces the defaults). Relying on the defaults keeps a consistent look across all JSON-UI surfaces.",
    ),
});

export type UniversalProps = z.infer<typeof UNIVERSAL_PROPS>;
